[package]
name = "kettlewin"
version = "0.1.0"
authors = ["Ian Kettlewell"]
edition = "2018"

[features]
gl_context = ["kettlewin_gl_context"]
default = ["gl_context"]

[dependencies]
kettlewin_gl_context = { path = "./gl_context", optional = true }

[dev-dependencies]
glow = {version = "0.4.0"}

[target.'cfg(target_os="macos")'.dependencies]
kettlewin_platform_macos = { path = "./platforms/macos" }

[target.'cfg(target_arch="wasm32")'.dependencies]
wasm-bindgen = "0.2.58"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.35"
features = [
    "console",
    "HtmlElement",
    "HtmlCanvasElement",
    "MouseEvent",
    "KeyboardEvent",
    "Event",
    "WebGlContextAttributes"
]
