[package]
name = "kapp"
version = "0.1.0"
authors = ["Ian Kettlewell"]
edition = "2018"

[features]
gl_context = ["kapp_gl_context"]
default = ["gl_context"]

[dependencies]
kapp_gl_context = { path = "./gl_context", optional = true }

[target.'cfg(target_os="macos")'.dependencies]
kapp_platform_macos = { path = "./platforms/macos" }

[target.'cfg(target_os="windows")'.dependencies]
kapp_platform_windows = { path = "./platforms/windows" }

[target.'cfg(target_arch="wasm32")'.dependencies]
kapp_platform_web = { path = "./platforms/web" }

