[package]
name = "kettlewin"
version = "0.1.0"
authors = ["Ian Kettlewell"]
edition = "2018"

[features]
default = ["opengl_glow"]
opengl_glow = ["glow"]

[dependencies]
glow = {version = "0.4.0", optional = true}

[target.'cfg(target_os="macos")'.dependencies]
cocoa = "0.20.0"
core-foundation = "0.7"
objc = "0.2.7"

[target.'cfg(target_os="windows")'.dependencies]
winapi = { version = "0.3.8", features = ["winuser", "libloaderapi", "windowsx"] }

[target.'cfg(target_arch="wasm32")'.dependencies]
wasm-bindgen = "0.2.58"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.35"
features = [
    "console",
    "HtmlElement",
    "HtmlCanvasElement",
    "MouseEvent",
    "KeyboardEvent",
    "Event",
]

[[example]]
name = "no_gl"
default-features = false
features = []

[[example]]
name = "hello"
required-features = ["opengl_glow"]
path = "examples/hello.rs"
