[package]
name = "kapp_platform_web"
version = "0.1.0"
authors = ["Ian Kettlewell <ian.kettlewell@gmail.com>"]
edition = "2018"

[dependencies]
kapp_platform_common = { path = "../../platform_common" }
wasm-bindgen = "0.2.64"
console_error_panic_hook = "0.1.6"

[dependencies.web-sys]
version = "0.3.35"
features = [
    "console",
    "Document",
    "HtmlElement",
    "HtmlCanvasElement",
    "MouseEvent",
    "PointerEvent",
    "KeyboardEvent",
    "WheelEvent",
    "Event",
    "WebGlContextAttributes",
    "Window"
]
