[package]
name = "kettlewin_platform_web"
version = "0.1.0"
authors = ["Ian Kettlewell <ian.kettlewell@gmail.com>"]
edition = "2018"

[dependencies]
kettlewin_platform_common = { path = "../../platform_common" }
wasm-bindgen = "0.2.58"

[dependencies.web-sys]
version = "0.3.35"
features = [
    "console",
    "HtmlElement",
    "HtmlCanvasElement",
    "MouseEvent",
    "KeyboardEvent",
    "Event",
    "WebGlContextAttributes"
]
