[package]
name = "kettlewin_platform_macos"
version = "0.1.0"
authors = ["Ian Kettlewell <ian.kettlewell@gmail.com>"]
edition = "2018"

[dependencies]
kettlewin_platform_common = { path = "../../platform_common" }
objc = { git = "https://github.com/kettle11/rust-objc" }