[package]
name = "kapp_platform_windows"
version = "0.1.0"
authors = ["Ian Kettlewell <ian.kettlewell@gmail.com>"]
edition = "2018"

[dependencies]
kapp_platform_common = { path = "../../platform_common" }